"""add unique constraint on username and source_site

Revision ID: 9a3529608280
Revises: f1ae2081e7c8
Create Date: 2025-06-13 21:14:38.517389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3529608280'
down_revision: Union[str, None] = 'f1ae2081e7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 대소문자 구분을 위해 collation을 binary로 설정
    op.execute("""
        ALTER TABLE user
        MODIFY username VARCHAR(255)
        CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL
    """)

    # 혹시 이미 있는 동일 제약 조건 먼저 제거 (있으면)
    op.drop_constraint("uq_username_source_site", "user", type_="unique", if_exists=True)
    # 유니크 제약 조건 추가
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_username_source_site', 'user', ['username', 'source_site'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_username_source_site', 'user', type_='unique')
    # ### end Alembic commands ###
