"""add is_blinded column to users

Revision ID: f1ae2081e7c8
Revises: 
Create Date: 2025-06-13 21:07:42.642001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ae2081e7c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comment_ibfk_1'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'deal', ['deal_id'], ['deal_id'])
    op.add_column('deal', sa.Column('is_blinded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'is_blinded')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_ibfk_1'), 'comment', 'deal', ['deal_id'], ['deal_id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # 유니크 제약 조건 삭제
    op.drop_constraint(
        "uq_username_source_site",
        "user",
        type_="unique"
    )

    # 다시 collation을 일반적인 걸로 복구
    op.execute("""
        ALTER TABLE user
        MODIFY username VARCHAR(255)
        CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
    """)
