import enum

class CacheKey(enum.Enum) :
    DEAL_ALL = "CACHE:DEAL:ALL"
    COMMENT_ALL = "CACHE:COMMENT:ALL"
    SITE_DEAL_COUNT = "CACHE:DEAL:SITE:COUNT"
    SITE_COMMENT_COUNT = "CACHE:COMMENT:SITE:COUNT"
    DEAL_SHAPE = "CACHE:DEAL:SHAPE"
    USER_SHAPE = "CACHE:USER:SHAPE"

